HackOkPlease/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^child/", include("HackOkapp.urls", namespace="child")),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^login/$", auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    url(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

HackOkapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'child'

urlpatterns=[
    url(r"^addinfo/$", views.HelperView, name='helper'),
    url(r"^searchinfo/$", views.PoliceView, name='police'),
    url(r"^result/$", views.ResultView, name='result'),
]

HackOkapp/models.py
from django.db import models

class Child(models.Model):
    name=models.CharField(max_length=256)
    age=models.IntegerField(null=True)
    child_pic = models.ImageField(upload_to = 'HackOkPlease/pic_folder/', default = 'HackOkapp/pic_folder/None/no-img.jpg',null=False)
    child_info=models.TextField(null=True)
    contact=models.CharField(null=True,max_length=256)

class Video(models.Model):
    location = models.CharField(max_length=500)
    videofile= models.FileField(upload_to='videos/', null=True, verbose_name="")

    def __str__(self):
        return self.name + ": " + str(self.videofile)

HackOkPlease/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super(UserCreationForm,self).__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

HackOkapp/forms.py
from django import forms
from . models import Child,Video

class ChildForm(forms.ModelForm):
    class Meta:
        model = Child
        fields = ('name','age','contact','child_pic')

class VideoForm(forms.ModelForm):
    class Meta:
        model= Video
        fields= ["location", "videofile"]

HackOkPlease/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy,reverse
from django.views.generic import CreateView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms

class HomePage(TemplateView):
    template_name = "index.html"


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

HackOkapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy,reverse
from django.views.generic import CreateView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from .models import Video,Child
from .forms import VideoForm,ChildForm
import sys
import argparse
import cv2
import numpy as np
import os
import face_recognition
import glob
from PIL import Image
from matplotlib import cm
from matplotlib import pyplot as plt
import imutils
import re

def PoliceView(request):
    if request.method == "POST":
        form = ChildForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            image1 = face_recognition.load_image_file('media/'+str(Child.objects.last().child_pic))
            list_of_face_encodings1 = face_recognition.face_encodings(image1)
            images = []
            for img in glob.glob("data/*"):
                print(img)
                image2 = face_recognition.load_image_file(img)
                list_of_face_encodings2 = face_recognition.face_encodings(image2)
                if len(list_of_face_encodings2) == 0:
                    continue
                results = face_recognition.compare_faces(list_of_face_encodings1, list_of_face_encodings2)
                print(results[0])
                if results[0] == True:
                    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                    url=os.path.join(BASE_DIR, img)
                    sentence = img
                    word = "_"
                    s=-1
                    e=-1
                    for match in re.finditer(word, sentence):
                        if e==-1:
                            e=match.end()
                        else:
                            s=match.start()
                    return render(request, 'result.html',{'text':'Person Found','found':'Person Found','location':sentence[e:s]})
            return render(request, 'result.html',{'text':'Person Not Found','found':'Person Found'})
        else:
            print("Form not valid")
    else:
        form = ChildForm()
    return render(request, 'policeinfo.html', {'form': form})

def facechop(img,location,currentFrame):  
    facedata = "media/haarcascade_frontalface_default.xml"
    cascade = cv2.CascadeClassifier(facedata)

    faces = cascade.detectMultiScale(img)

    for f in faces:
        x, y, w, h = [ v for v in f ]
        sub_face = img[y:y+h, x:x+w]
        file_name = "data/frame" + "_" + location + "_" + str(currentFrame) + ".jpg"
        cv2.imwrite(file_name, sub_face)

def HelperView(request):
    if request.method == "POST":
        print(request.FILES['videofile'])
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            FPS = 10
            cap = cv2.VideoCapture('media/'+str(Video.objects.last().videofile))
            cap.set(cv2.CAP_PROP_FPS, FPS)
            j=cap.get(cv2.CAP_PROP_FPS)
            print(j)
            try:
                if not os.path.exists('data'):
                    os.makedirs('data')
            except OSError:
                print ('Error: Creating directory of data')
            currentFrame = 0
            while(True):
                ret, frame = cap.read()
                if not ret: break
                rotated_frame = imutils.rotate_bound(frame, 90)
                facechop(rotated_frame,request.POST['location'],currentFrame)
                print ('Creating...' + str(currentFrame))
                currentFrame += 1
            cap.release()
            cv2.destroyAllWindows()
            return redirect('home')
        else:
            print("Form not valid")
    else:
        form = VideoForm()
    return render(request, 'helper.html', {'form': form})

def ResultView(request):
    return render(request,"result.html")

HackOkapp/templates/helper.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block headblock %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1 align=center style="font-family:Times New Roman">JUST UPLOAD THE VIDEO AND ADD THE EXACT LOCATION TOO.</h1>
    <br>
    <h1>Video Uploader</h1><p>
    <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload"/>
    </form>
  </div>
{% endblock %}

HackOkapp/templates/policeinfo.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block headblock %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1 align=center style="font-family:Times New Roman">UPLOAD THE PHOTO AND OTHER DETAILS MENTIONED IN THE MISSING REPORT</h1>
    <br>
    <!-- <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Yaayy Submit" class="btn btn-default">
    </form> -->
    <form method="post" class="form" align=center enctype="multipart/form-data">
    {% csrf_token %}
    <label>Missing person's full name</label>
		<br>
		{{ form.name }}
		<br>
    <br>
    <label>Missing person's age</label>
		<br>
		{{ form.age }}
		<br>
    <br>
    <label>Local Guardian's contact details</label>
		<br>
		{{ form.contact }}
		<br>
    <br>
		<label>Upload the photo you have clicked</label>
		<br>
		<label align="center" style="padding-left:80px;">{{ form.child_pic }}</label>
		<br>
		<br>
    <button class="btn btn-outline-primary" type="submit" align="center">Find the missing person!</button>
  </form>
</div>
{% endblock %}

HackOkapp/templates/result.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block headblock %}

 <link rel="stylesheet" type="text/css" href="{% static 'res.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h2 align=center style="font-family:Times New Roman;">{{ text }}</h2>
    {% if text == found %}
    <h3 align=center style="font-family:Times New Roman;">In {{ location }}</h3>
    {% endif %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Cuidate</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    {% block headblock %}
    {% endblock %}

  </head>
  <body style="padding-top:10px;">
    <nav class="navbar mynav" role="navigation" id="navbar">
    			<div class="container">
            <a class="navbar-brand btn btn-default" href="{% url 'home' %}">
              <span class='glyphicon glyphicon-home'>
               </span>
            </a>
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}"><button type="button" class="btn btn-primary">LogOut</button></a></li>
    						{% else %}
                      <li><a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Login</button></a></li>
                      <li><p></p></li>
    						      <li><a href="{% url 'signup' %}"><button type="button" class="btn btn-primary">Sign Up</button></a></li>
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        {% block fullscreen %}
        {% endblock %}
        <div class="container mycontent">
          {% block content %}

          {% endblock %}
        </div>

  <canvas id="canvas"></canvas>

  </body>
  <!-- <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->
</html>

templates/index.html
{% extends "base.html" %}
{% block headblock %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}

<div class="index-banner" style="margin-top:0px;">
  <div class="index-banner-bg"><img src="https://png.pngtree.com/thumb_back/fw800/back_pic/05/12/58/9559999fc3af68b.jpg" alt="banner" style="opacity:0.5;/></div>
  <div class="index-banner-text">
      <h1 align="center" style="color:#374760;font-size:180px;" class="head_mansi">Cuidate</h1>
    <div class="text-logo"></div>
    <p class="text-info">
      <i class="line line-left"></i>
      <span class="under_tag" style="color:#374760;font-size:60px;padding-left:60px;">Unite lost children with their parents
</span><i class="line line-right"></i>
    </p>
  </div>
</div>

{% if user.is_authenticated %}
<a href="{% url 'child:police' %}" class='sell' style="color:#2d2f33;">POLICE! UPLOAD DETAILS OF A LOST KID!</a>
{% else %}
<a href="{% url 'child:helper' %}" class='sell' style="color:#2d2f33;">CLICK HERE TO UPLOAD VIDEO!</a>
{% endif %}


<style media="screen">
.sell{
  text-align: center;
    display:block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:white;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:white;
  font-size: 100px;
  font-family: 'Poor Story', cursive;
}
.index-banner {
  position: relative;
  background: #b3b3b3;
}
.index-banner-bg {
  height: 500px;
  overflow: hidden;
}
.index-banner-bg img {
  margin: 0 auto;
  position: absolute;
  height: 540px;
  width: 1500px;
}
.index-banner-text {
  position: absolute;
  top: 100px;
  left: 50%;
   margin-left: -430px;
}
.index-banner-text .text-logo {
  width: 776px;
  height: 117px;

  no-repeat;
}
.index-banner-text .text-info {
  margin-top: 10px;
  text-align: center;
  color: #fff;
}
.index-banner-text .text-info .line {
  display: inline-block;
  width: 40px;
  border-top: 1px solid #fff;
  vertical-align: middle;
  *margin-top: 22px;
}
.index-banner-text .text-info .text {
  margin: 0 26px;
}


.index-panel {
  margin: 0 auto;
  margin-top: 200px;
  position: relative;
  width: 1100px;
}
.inedx-panel-header {
}
.inedx-panel-header h3 {
  float: left;
  margin-right: 48px;
  font-size: 20px;
  color: #3b3b3b;
  font-weight: normal;
}
.inedx-panel-header .line {
  float: left;
  margin-top: 10px;
  width: 200px;
  border-top: 1px solid #e5e3e3;
}
.inedx-panel-header .btn-group {
  font-size: 0;
  float: right;
}
.inedx-panel-header .btn {
  display: inline-block;
  margin-left: 11px;
  width: 9px;
  height: 9px;
  background: #dedede;
  border-radius: 50%;
  -moz-border-radius: 50%;
  -webkit-border-radius: 50%;
}
.inedx-panel-header .active {
  background: #9b9b9b;
}
.index-panel-body {
  margin-top: 75px;
}
.index-food-list {
  overflow: hidden;
}
.index-food-list ul {
  width: 1160px;
}
.index-food-list .food-item {
  float: left;
  width: 230px;
  margin-right: 60px;
}
.index-food-list .food-item .banner {
  margin-bottom: 30px;
  height: 202px;
}
.index-food-list .food-item .name {
  color: #555;
  margin-bottom: 10px;
}
.index-food-list .food-item .star-bar {
  font-size: 0;
}
.index-food-list .food-item .star {
  display: inline-block;
  width: 12px;
  height: 13px;
  margin-right: 5px;
  background-image: url("https://github.com/JessicaPotter2/foodWebsite/blob/master/images/star.png?raw=true");
  background-repeat: no-repeat;
}
.index-food-list .food-item .no-star {
  background-position: 0 -13px;
}
.index-food-list .food-item .price {
  float: right;
}
.index-pics {
  height: 380px;
  overflow: hidden;
}
.index-pics .pic-col {
  float: left;
}
.index-pics .pic-col-l {
  width: 460px;
}
.index-pics .pic-col-m {
  width: 352px;
}
.index-pics .pic-col-s {
  width: 288px;
}
.public-header {
  height: 110px;
}
.public-header .header-logo {
  margin-top: 40px;
  float: left;
}
.public-header .header-logo a {
  width: 182px;
  height: 54px;
  background: url("https://github.com/JessicaPotter2/foodWebsite/blob/master/images/index-header-logo.png?raw=true")
    no-repeat;
}
.public-header .header-nav a:hover {
  text-decoration: underline;
}
.public-header .header-nav {
  float: right;
  font-size: 14px;
}
.public-header .header-nav .item {
  float: left;
  margin-top: 44px;
  margin-left: 44px;
}
.public-header .header-nav a {
  color: #3b3b3b;
}
.public-container {
  position: relative;
  margin: 0 auto;
  width: 1100px;
}
.public-footer {
  height: 218px;
  padding-top: 100px;
  margin-top: 200px;
  background: #3b3b3b;
}
.public-footer .footer-col {
  width: 230px;
  float: left;
  margin-right: 60px;
  font-size: 16px;
  color: #fff;
  line-height: 1.8;
}
.public-footer .footer-col-nor {
  margin-right: 0;
}
.public-footer .footer-logo {
  width: 182px;
  height: 55px;
  margin-top: -15px;
  margin-bottom: 12px;
  background: url("https://github.com/JessicaPotter2/foodWebsite/blob/master/images/index-footer-logo.png?raw=true")
    no-repeat;
}
.footer-info a {
  display: inline-block;
  font-size: 18px;
  font-weight: bold;
}

</style>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block headblock %}
 <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}">
 <script src="{% static "js/login.js" %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="container jumbotron">
    <h1>LOGIN</h1>
    <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <script>
        function clickAlert() {
          alert("You are now logged in!");
        }
      </script>
<input type="submit" onclick="clickAlert()" value="Login" class="btn btn-default button button-block">
        <!-- <input type="submit" value="Login" class="btn btn-default button button-block"> -->
    </form>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block headblock %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container jumbotron">
    <h1>SIGN UP!</h1>
    <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}